spring:
  application:
    name: movieflix
  
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo_filmes_db
    username: emilianno
    password: adm
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    
  flyway:
    enabled: true
    
  movieflix:
    security:
      secret: "5J0xS7dE9hB1F2k93xMZz7rNlg6VFeJzKZx7gH5Q3JpA6VqH7TjW8zD2lC9mXyPn"
    


